//#include source/Component.js
//#include source/core.js
//#include source/document.js
//#include source/Element.js
//#include source/EventObject.js
//#include source/Observer.js
//#include source/Widget.js
//#include source/XHR.js
//#include source/lang/Array.js
//#include source/lang/Date.js
//#include source/lang/Function.js
//#include source/lang/Number.js
//#include source/lang/JSON.js
//#include source/lang/String.js
//#include source/lang/XMLHttpRequest.js
//#include source/Timer.js
//#include source/cookie.js